-- CreateEnum
CREATE TYPE "video_status" AS ENUM ('awaiting_upload', 'processing', 'ready', 'failed');

-- CreateEnum
CREATE TYPE "post_visibility" AS ENUM ('public', 'private');

-- CreateEnum
CREATE TYPE "interaction_type" AS ENUM ('impression', 'play', 'complete', 'like', 'save', 'share', 'profile_visit', 'follow');

-- AlterTable
ALTER TABLE "posts" ADD COLUMN     "category_id" UUID,
ADD COLUMN     "learn_materials" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "learn_tips" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "learn_tools" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "processing_error" VARCHAR(300),
ADD COLUMN     "published_at" TIMESTAMPTZ(6),
ADD COLUMN     "status" "video_status" NOT NULL DEFAULT 'ready',
ADD COLUMN     "thumbnail_storage_key" VARCHAR(200),
ADD COLUMN     "video_height" INTEGER,
ADD COLUMN     "video_mime_type" VARCHAR(50),
ADD COLUMN     "video_size_bytes" INTEGER,
ADD COLUMN     "video_storage_key" VARCHAR(200),
ADD COLUMN     "video_width" INTEGER,
ADD COLUMN     "visibility" "post_visibility" NOT NULL DEFAULT 'public';

-- CreateTable
CREATE TABLE "interaction_events" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "type" "interaction_type" NOT NULL,
    "user_id" UUID,
    "post_id" UUID,
    "creator_id" UUID,
    "watch_ms" INTEGER,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "interaction_events_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "idx_interaction_events_post" ON "interaction_events"("post_id", "type", "created_at");

-- CreateIndex
CREATE INDEX "idx_interaction_events_user" ON "interaction_events"("user_id", "created_at");

-- CreateIndex
CREATE INDEX "idx_interaction_events_creator" ON "interaction_events"("creator_id", "type");

-- CreateIndex
CREATE UNIQUE INDEX "posts_video_storage_key_key" ON "posts"("video_storage_key");

-- CreateIndex
CREATE INDEX "idx_posts_video_feed" ON "posts"("status", "is_published", "visibility", "published_at" DESC);

-- CreateIndex
CREATE INDEX "idx_posts_category_id" ON "posts"("category_id");

-- AddForeignKey
ALTER TABLE "posts" ADD CONSTRAINT "posts_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "interaction_events" ADD CONSTRAINT "interaction_events_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "interaction_events" ADD CONSTRAINT "interaction_events_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "interaction_events" ADD CONSTRAINT "interaction_events_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ─── Constraints ─────────────────────────────────────────────────────────────

-- Only a fully processed video can be published.
ALTER TABLE "posts"
  ADD CONSTRAINT "posts_published_requires_ready" CHECK (NOT "is_published" OR "status" = 'ready'),
  -- Storage keys are generated by the server in one fixed shape (no paths from clients).
  ADD CONSTRAINT "posts_video_storage_key_format" CHECK (
    "video_storage_key" IS NULL
    OR "video_storage_key" ~ '^videos/[0-9a-f-]{36}\.(mp4|mov)$'
  ),
  ADD CONSTRAINT "posts_thumbnail_storage_key_format" CHECK (
    "thumbnail_storage_key" IS NULL
    OR "thumbnail_storage_key" ~ '^thumbnails/[0-9a-f-]{36}\.jpg$'
  ),
  ADD CONSTRAINT "posts_video_size_positive" CHECK ("video_size_bytes" IS NULL OR "video_size_bytes" > 0),
  ADD CONSTRAINT "posts_video_dimensions_positive" CHECK (
    ("video_width" IS NULL OR "video_width" > 0) AND ("video_height" IS NULL OR "video_height" > 0)
  ),
  ADD CONSTRAINT "posts_learn_lists_small" CHECK (
    coalesce(cardinality("learn_tools"), 0) <= 10
    AND coalesce(cardinality("learn_materials"), 0) <= 10
    AND coalesce(cardinality("learn_tips"), 0) <= 5
  );

ALTER TABLE "interaction_events"
  ADD CONSTRAINT "interaction_events_watch_ms_non_negative" CHECK ("watch_ms" IS NULL OR "watch_ms" >= 0);
