// Video storage abstraction. The post system only talks to `VideoStorage`, so a real object
// store (S3, R2, GCS...) can be added later without touching posts, routes or the app.
import { createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { createReadStream, type ReadStream } from 'node:fs';
import { copyFile, mkdir, rm, stat } from 'node:fs/promises';
import path from 'node:path';
import type { Env } from '../../config/env.js';

/**
 * Keys are generated by the server only, in one fixed shape. Anything else (paths, "..",
 * user-supplied names) is rejected before touching storage.
 */
export const STORAGE_KEY_PATTERN =
  /^(videos\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(mp4|mov)|(thumbnails|avatars)\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.jpg)$/;

export function assertStorageKey(key: string): void {
  if (!STORAGE_KEY_PATTERN.test(key)) throw new Error(`Invalid storage key: ${key}`);
}

export const CONTENT_TYPES: Record<string, string> = {
  mp4: 'video/mp4',
  mov: 'video/quicktime',
  jpg: 'image/jpeg',
};

export interface VideoStorage {
  readonly name: string;
  /** True for storage that must never run in production (e.g. the local disk). */
  readonly isDevelopmentOnly: boolean;
  /** Copies an already-verified local file into storage under `key`. */
  put(key: string, sourcePath: string): Promise<void>;
  /** Removes an object. Missing objects are fine. */
  delete(key: string): Promise<void>;
  /** A URL a client can use for `ttlSeconds`: absolute, or relative to the API origin. */
  url(key: string, ttlSeconds: number): string;
}

/** Signs and checks expiring media URLs (HMAC-SHA256 over key + expiry). */
export class MediaSigner {
  constructor(
    private readonly secret: string,
    private readonly now: () => number = Date.now,
  ) {}

  private mac(key: string, exp: number): string {
    return createHmac('sha256', this.secret).update(`${key}\n${exp}`).digest('base64url');
  }

  sign(key: string, ttlSeconds: number): { exp: number; sig: string } {
    const exp = Math.floor(this.now() / 1000) + ttlSeconds;
    return { exp, sig: this.mac(key, exp) };
  }

  verify(key: string, exp: number, sig: string): boolean {
    if (!Number.isInteger(exp) || exp < Math.floor(this.now() / 1000)) return false;
    const expected = Buffer.from(this.mac(key, exp));
    const given = Buffer.from(sig);
    return expected.length === given.length && timingSafeEqual(expected, given);
  }
}

/**
 * DEVELOPMENT ONLY: stores files on this machine's disk and serves them through the API's
 * /media route with signed, expiring URLs. Not durable, not shared between servers, no CDN.
 * The API refuses to start in production with it.
 */
export class LocalDiskStorage implements VideoStorage {
  readonly name = 'local-disk (development only)';
  readonly isDevelopmentOnly = true;

  constructor(
    readonly root: string,
    private readonly signer: MediaSigner,
  ) {}

  /** Absolute path for a key, guaranteed to stay inside the storage root. */
  pathFor(key: string): string {
    assertStorageKey(key);
    const full = path.resolve(this.root, key);
    const root = path.resolve(this.root) + path.sep;
    if (!full.startsWith(root)) throw new Error('Storage path escapes the root');
    return full;
  }

  async put(key: string, sourcePath: string): Promise<void> {
    const target = this.pathFor(key);
    await mkdir(path.dirname(target), { recursive: true });
    await copyFile(sourcePath, target);
  }

  async delete(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }

  url(key: string, ttlSeconds: number): string {
    assertStorageKey(key);
    const { exp, sig } = this.signer.sign(key, ttlSeconds);
    return `/api/v1/media/${key}?exp=${exp}&sig=${sig}`;
  }

  async size(key: string): Promise<number | null> {
    try {
      return (await stat(this.pathFor(key))).size;
    } catch {
      return null;
    }
  }

  read(key: string, range?: { start: number; end: number }): ReadStream {
    return createReadStream(this.pathFor(key), range);
  }
}

export interface VideoStorageSetup {
  storage: VideoStorage | null;
  signer: MediaSigner;
  /** Why uploads are off, when `storage` is null. */
  unavailableReason: string | null;
}

/** Builds storage from the environment. Production never falls back to local storage. */
export function videoStorageFromEnv(
  env: Pick<Env, 'NODE_ENV' | 'VIDEO_STORAGE' | 'VIDEO_STORAGE_DIR' | 'MEDIA_SIGNING_SECRET'>,
): VideoStorageSetup {
  const secret =
    env.MEDIA_SIGNING_SECRET ??
    (env.NODE_ENV === 'production' ? null : randomBytes(32).toString('base64url'));
  const signer = new MediaSigner(secret ?? randomBytes(32).toString('base64url'));

  if (env.VIDEO_STORAGE === 'local') {
    if (env.NODE_ENV === 'production') {
      // loadEnv() already refuses this; kept here so storage can never be misused.
      throw new Error('VIDEO_STORAGE=local cannot be used in production');
    }
    return {
      storage: new LocalDiskStorage(path.resolve(env.VIDEO_STORAGE_DIR), signer),
      signer,
      unavailableReason: null,
    };
  }
  return {
    storage: null,
    signer,
    unavailableReason: 'Video storage is not configured on this server',
  };
}
